-- Clean it up
MinimapCluster:SetScale(1)
MinimapCluster:SetPoint("TOPRIGHT", "UIParent", "TOPRIGHT", 2, 0)
MinimapZoomIn:Hide()
MinimapZoomOut:Hide()
MiniMapWorldMapButton:Hide()
MinimapZoneTextButton:Show()
MinimapBorderTop:Hide()
GameTimeFrame:Hide()
-- Minimap scrolling (Credit: Thek)
